events { 
    worker_connections 1024; 
}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;

            # Aktiviert das Sub-Modul: Sucht nach ##SERVERNAME## und ersetzt es mit dem Hostnamen
            sub_filter '##SERVERNAME##' $hostname;
            sub_filter_once on;
        }

        access_log /logs/web1_access.log;
        error_log  /logs/web1_error.log;
    }
}