events { 
    worker_connections 1024; 
}

http {
    upstream mein_cluster {
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://mein_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        access_log /logs/lb_access.log;
        error_log  /logs/lb_error.log;
    }
}
